name: Build Production Image
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+' # like v4.3.0-1

jobs:
  build-ap-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: metadata
        run: |
          echo "tag_name=${TAG_NAME##refs/tags/v}" >> "${GITHUB_OUTPUT}"
        env:
          TAG_NAME: ${{ github.ref }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.metadata.outputs.tag_name }}

  build-streaming-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: metadata
        run: |
          echo "tag_name=${TAG_NAME##refs/tags/v}" >> "${GITHUB_OUTPUT}"
        env:
          TAG_NAME: ${{ github.ref }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: streaming/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}-streaming:${{ steps.metadata.outputs.tag_name }}
